init:
  - "SET PATH=C:\\Python38\\Scripts;%PATH%"
  - "SET PYTEST_ADDOPTS=-vv"
  - "ECHO PATH=%PATH%"

build: off

install:
  - pip3 install poetry
  - poetry install

test_script:
  - poetry run pytest tests/ -s --cov=isort/ --cov=tests/ --cov-report=term-missing --cov-report html
